/**
 * @author Hiudy · github.com/hiudyy
 * @project Misa Bot
 */

export type FunTrait = {
  name: string;
  aliases?: string[];
};

/** Porcentagens — masculino */
export const MALE_PERCENT_TRAITS: FunTrait[] = [
  { name: "gay" },
  { name: "burro" },
  { name: "inteligente" },
  { name: "otaku" },
  { name: "fiel" },
  { name: "infiel" },
  { name: "corno" },
  { name: "gado" },
  { name: "gostoso" },
  { name: "feio" },
  { name: "rico" },
  { name: "pobre" },
  { name: "pirocudo", aliases: ["pirokudo"] },
  { name: "nazista" },
  { name: "ladrao" },
  { name: "safado" },
  { name: "vesgo" },
  { name: "bebado" },
  { name: "machista" },
  { name: "homofobico" },
  { name: "racista" },
  { name: "chato" },
  { name: "sortudo", aliases: ["sortudo2"] },
  { name: "azarado" },
  { name: "forte" },
  { name: "fraco" },
  { name: "pegador" },
  { name: "otario" },
  { name: "macho" },
  { name: "bobo" },
  { name: "nerd" },
  { name: "preguicoso" },
  { name: "trabalhador" },
  { name: "brabo" },
  { name: "lindo" },
  { name: "malandro" },
  { name: "simpatico" },
  { name: "engracado" },
  { name: "charmoso" },
  { name: "misterioso" },
  { name: "carinhoso" },
  { name: "desumilde" },
  { name: "humilde" },
  { name: "ciumento" },
  { name: "corajoso" },
  { name: "covarde" },
  { name: "esperto" },
  { name: "talarico" },
  { name: "chorao" },
  { name: "brincalhao" },
  { name: "bolsonarista" },
  { name: "petista" },
  { name: "comunista" },
  { name: "lulista" },
  { name: "traidor" },
  { name: "bandido" },
  { name: "cachorro" },
  { name: "vagabundo" },
  { name: "pilantra" },
  { name: "mito" },
  { name: "padrao" },
  { name: "comedia" },
  { name: "psicopata" },
  { name: "fortao" },
  { name: "magrelo" },
  { name: "bombado" },
  { name: "chefe" },
  { name: "presidente" },
  { name: "rei" },
  { name: "patrao" },
  { name: "playboy" },
  { name: "zueiro", aliases: ["zueira"] },
  { name: "gamer" },
  { name: "programador" },
  { name: "visionario" },
  { name: "billionario", aliases: ["bilionario"] },
  { name: "poderoso" },
  { name: "vencedor" },
  { name: "senhor" },
  { name: "fofoqueiro" },
  { name: "dorminhoco" },
  { name: "comilao" },
  { name: "sedentario" },
  { name: "atleta" },
  { name: "estudioso" },
  { name: "romantico" },
  { name: "extrovertido" },
  { name: "introvertido" },
  { name: "calmo" },
  { name: "nervoso" },
  { name: "organizado" },
  { name: "bagunceiro" },
  { name: "economico" },
  { name: "gastador" },
  { name: "saudavel" },
  { name: "doente" },
  { name: "supersticioso" },
  { name: "cetico" },
  { name: "religioso" },
  { name: "ateu" },
  { name: "tradicional" },
  { name: "moderno" },
  { name: "conservador" },
  { name: "liberal" },
  { name: "patriotico" },
  { name: "cosmopolita" },
  { name: "rural" },
  { name: "urbano" },
  { name: "aventureiro" },
  { name: "caseiro" },
  { name: "viajante" },
  { name: "local" },
  { name: "global" },
  { name: "tecnologico" },
  { name: "analogico" },
  { name: "digital" },
  { name: "offline" },
  { name: "online" },
  { name: "social" },
  { name: "antisocial" },
  { name: "popular" },
  { name: "solitario" },
  { name: "lider" },
  { name: "seguidor" },
  { name: "independente" },
  { name: "dependente" },
  { name: "criativo" },
  { name: "pratico" },
  { name: "sonhador" },
  { name: "realista" },
  { name: "otimista" },
  { name: "pessimista" },
  { name: "confiante" },
  { name: "inseguro" },
  { name: "maduro" },
  { name: "infantil" },
  { name: "serio" },
  { name: "responsavel" },
  { name: "irresponsavel" },
];

/** Porcentagens — feminino */
export const FEMALE_PERCENT_TRAITS: FunTrait[] = [
  { name: "lesbica" },
  { name: "burra" },
  { name: "corna" },
  { name: "gostosa" },
  { name: "feia" },
  { name: "rica" },
  { name: "bucetuda" },
  { name: "ladra" },
  { name: "safada" },
  { name: "vesga" },
  { name: "bebada" },
  { name: "homofobica" },
  { name: "chata" },
  { name: "sortuda" },
  { name: "azarada" },
  { name: "fraca" },
  { name: "pegadora" },
  { name: "otaria" },
  { name: "boba" },
  { name: "preguicosa" },
  { name: "trabalhadora" },
  { name: "braba" },
  { name: "linda" },
  { name: "malandra" },
  { name: "simpatica" },
  { name: "engracada" },
  { name: "charmosa" },
  { name: "misteriosa" },
  { name: "carinhosa" },
  { name: "ciumenta" },
  { name: "corajosa" },
  { name: "esperta" },
  { name: "talarica" },
  { name: "chorona" },
  { name: "brincalhona" },
  { name: "traidora" },
  { name: "bandida" },
  { name: "cachorra" },
  { name: "vagabunda" },
  { name: "fortona" },
  { name: "magrela" },
  { name: "bombada" },
  { name: "presidenta" },
  { name: "rainha" },
  { name: "patroa" },
  { name: "programadora" },
  { name: "visionaria" },
  { name: "bilionaria" },
  { name: "poderosa" },
  { name: "vencedora" },
  { name: "senhora" },
  { name: "fofoqueira" },
  { name: "dorminhoca" },
  { name: "comilona" },
  { name: "sedentaria" },
  { name: "estudiosa" },
  { name: "romantica" },
  { name: "extrovertida" },
  { name: "introvertida" },
  { name: "calma" },
  { name: "nervosa" },
  { name: "organizada" },
  { name: "bagunceira" },
  { name: "economica" },
  { name: "gastadora" },
  { name: "supersticiosa" },
  { name: "cetica" },
  { name: "religiosa" },
  { name: "ateia" },
  { name: "moderna" },
  { name: "conservadora" },
  { name: "patriotica" },
  { name: "urbana" },
  { name: "aventureira" },
  { name: "caseira" },
  { name: "tecnologica" },
  { name: "analogica" },
  { name: "solitaria" },
  { name: "seguidora" },
  { name: "criativa" },
  { name: "pratica" },
  { name: "sonhadora" },
  { name: "insegura" },
  { name: "madura" },
  { name: "seria" },
];

/** Ranks — masculino (nome canônico sem plural) */
export const MALE_RANK_TRAITS: FunTrait[] = [
  { name: "rankgay", aliases: ["rankgays"] },
  { name: "rankburro", aliases: ["rankburros"] },
  { name: "rankinteligente", aliases: ["rankinteligentes"] },
  { name: "rankotaku", aliases: ["rankotakus"] },
  { name: "rankfiel", aliases: ["rankfiels"] },
  { name: "rankinfiel", aliases: ["rankinfieis"] },
  { name: "rankcorno", aliases: ["rankcornos"] },
  { name: "rankgado", aliases: ["rankgados"] },
  { name: "rankgostoso", aliases: ["rankgostosos"] },
  { name: "rankrico", aliases: ["rankricos"] },
  { name: "rankpobre", aliases: ["rankpobres"] },
  { name: "rankforte", aliases: ["rankfortes"] },
  { name: "rankpegador", aliases: ["rankpegadores"] },
  { name: "rankmacho", aliases: ["rankmachos"] },
  { name: "ranknerd", aliases: ["ranknerds"] },
  { name: "ranktrabalhador", aliases: ["ranktrabalhadores"] },
  { name: "rankbrabo", aliases: ["rankbrabos"] },
  { name: "ranklindo", aliases: ["ranklindos"] },
  { name: "rankmalandro", aliases: ["rankmalandros"] },
  { name: "rankengracado", aliases: ["rankengracados"] },
  { name: "rankcharmoso", aliases: ["rankcharmosos"] },
  { name: "rankvisionario", aliases: ["rankvisionarios"] },
  { name: "rankpoderoso", aliases: ["rankpoderosos"] },
  { name: "rankvencedor", aliases: ["rankvencedores"] },
];

/** Ranks — feminino */
export const FEMALE_RANK_TRAITS: FunTrait[] = [
  { name: "ranklesbica", aliases: ["ranklesbicas"] },
  { name: "rankburra", aliases: ["rankburras"] },
  { name: "rankcorna", aliases: ["rankcornas"] },
  { name: "rankgada", aliases: ["rankgads", "rankgadas"] },
  { name: "rankgostosa", aliases: ["rankgostosas"] },
  { name: "rankrica", aliases: ["rankricas"] },
  { name: "rankpegadora", aliases: ["rankpegadoras"] },
  { name: "ranktrabalhadora", aliases: ["ranktrabalhadoras"] },
  { name: "rankbraba", aliases: ["rankbrabas"] },
  { name: "ranklinda", aliases: ["ranklindas"] },
  { name: "rankmalandra", aliases: ["rankmalandras"] },
  { name: "rankengracada", aliases: ["rankengracadas"] },
  { name: "rankcharmosa", aliases: ["rankcharmosas"] },
  { name: "rankvisionaria", aliases: ["rankvisionarias"] },
  { name: "rankpoderosa", aliases: ["rankpoderosas"] },
  { name: "rankvencedora", aliases: ["rankvencedoras"] },
];

export const FUN_RANK_MIN_MEMBERS = 5;
export const FUN_RANK_SIZE = 5;

/** Interações com vídeo (games2) — canônico + aliases */
export const INTERACTION_ACTIONS: FunTrait[] = [
  { name: "chute", aliases: ["chutar"] },
  { name: "tapa", aliases: ["tapar"] },
  { name: "soco", aliases: ["socar"] },
  { name: "beijo", aliases: ["beijar", "beijob", "beijarb"] },
  { name: "abraco", aliases: ["abracar"] },
  { name: "mata", aliases: ["matar"] },
  { name: "sexo" },
  { name: "goza", aliases: ["gozar"] },
  { name: "mamar", aliases: ["mamada"] },
  { name: "cafune" },
  { name: "morder", aliases: ["mordida"] },
  { name: "lamber", aliases: ["lambida"] },
  { name: "explodir" },
  { name: "tomate" },
];

export function randomPercent(): number {
  return Math.floor(Math.random() * 101);
}

export function pickRandomMembers(members: string[], size: number): string[] {
  const shuffled = [...members].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, size);
}

export function traitLabelFromRank(commandName: string): string {
  return commandName.replace(/^rank/, "");
}
